name: rudaelmoslem
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+3

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  easy_localization: ^3.0.0


  cupertino_icons: ^1.0.3
  provider: ^6.0.1
  universal_io: ^2.0.4
  #shared_preferences: ^2.0.8
  geolocator: ^7.6.2
  flutter_svg: ^0.22.0
  archive: ^3.1.2
  dio: ^4.0.0
  path_provider: ^2.0.8
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  persian: ^1.1.1
  equatable: ^2.0.3
  http: ^0.13.3
  flutter_share: ^2.0.0
  flutter_compass: ^0.7.0
 
  intl: ^0.17.0
  scoped_model: ^1.1.0
 
  flutter_qiblah: ^2.0.2
  flutter_bloc: ^7.3.0
  json_annotation: ^4.1.0
  shimmer: ^2.0.0
  geocoding: ^2.0.1
  logger: ^1.1.0
  global_configuration: ^2.0.0-nullsafety.1
  retrofit: ^2.0.1
  adhan: ^2.0.0-nullsafety.2
  location: ^4.3.0
  get_storage: ^2.0.3
  
  firebase_core: ^1.10.6
  cloud_firestore: ^3.1.5
  firebase_remote_config: ^0.11.0
  firebase_storage: ^10.0.5
  #firebase_messaging: ^11.2.4
  firebase_analytics: ^9.0.4
  fcm_config: ^3.3.3
  google_mobile_ads: ^1.0.0
  huawei_ads: ^13.4.45+308

  timezone: ^0.8.0
 
  flutter_native_timezone: ^2.0.0
  font_awesome_flutter: ^9.1.0
  package_info: ^2.0.2
  app_settings: ^4.1.1
  restart_app: ^1.1.0
  fluttertoast: ^8.0.8
  rxdart: ^0.27.2
  in_app_review: ^2.0.3
  introduction_screen: ^2.1.0
  flutter_spinkit: ^5.1.0
  grouped_list: ^4.1.0
  #flutter_countdown_timer: ^4.1.0

  #android_alarm_manager: ^2.0.2
  #workmanager: ^0.4.1
  #background_fetch: ^1.0.3
  #flutter_local_notifications: ^9.1.5
  
  custom_timer: ^0.0.6
  audioplayers: ^0.20.1
  flutter_cached_pdfview: ^0.4.0-nullsafety
  pdf_image_renderer: ^0.6.1
  decoding_text_effect: ^1.1.1
  salomon_bottom_bar: ^3.1.0
  
  bubble_overlay: ^0.2.0

  animate_do: ^2.0.0
  #--
  package_info_plus: ^1.3.0
  device_info_plus: ^3.1.1
  
  #adhan_flutter:
  #flutter_adhan: ^1.0.1

  # azan_local_notifications:
  #   path: azan_notifications/azan_local_notifications
  azan_local_notifications: ^0.0.2

  device_preview: ^1.0.0
      

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/
      - assets/icons/
      - assets/quran/
      - assets/quranIndex/
      - assets/pdf/
      - assets/svg/
      - assets/audio/saly/
      - assets/audio/azan/
      - assets/json/
      - assets/json/azkar/
      - assets/json/prayer/
      - assets/json/islamic/
      - assets/json/quran/
      - assets/json/surah/
      - assets/translations/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
        - asset: fonts/Cairo-Bold.ttf
          #style: Bold
    - family: Mada
      fonts:
        - asset: fonts/Mada-Regular.ttf
        - asset: fonts/Mada-Bold.ttf
          #weight: 700
    - family: Kufi
      fonts:
        - asset: fonts/ReemKufi-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
