import 'package:intl/intl.dart';

/// Jakim E-solat API model.
/// Generated by https://jsontodart.zariman.dev/
class JakimEsolatModel {
  List<PrayerTimeNotifi>? prayerTime;
  //String? status;
 // String? serverTime;
  // String? periodType;
  // String? lang;
  //String? zone;
  // String? bearing;

  JakimEsolatModel({
    this.prayerTime,
   // this.status,
    //this.serverTime,
    // this.periodType,
    // this.lang,
    //this.zone,
    // this.bearing
  });

  JakimEsolatModel.fromJson(Map<String, dynamic> json) {
    //prayerTime = json["prayerTime"].map((e) => PrayerTimeNotifi.fromJson(e)).toList();
    prayerTime = List.from(json['prayerTime']).map((e)=>PrayerTimeNotifi.fromJson(e)).toList();
    //List<SuraList>? suras = await jsonResponse.map<SuraList>((json) => SuraList.fromJson(json)).toList();
   // status = json["status"];
    //serverTime = json["serverTime"];
    // periodType = json["periodType"];
    // lang = json["lang"];
    //zone = json["zone"];
    // bearing = json["bearing"];
  }
}

class PrayerTimeNotifi {
  List<int>? times;
  String? date;
   String? imsak;
   String?fajr;
   String? syuruk;
   String? dhuhr;
   String? asr;
   String? maghrib;
   String? isha;

  PrayerTimeNotifi({
    this.times,
      this.date,
      this.dhuhr,
      this.imsak ,
     this.fajr ,
     this.syuruk ,
     this.asr,
    this.maghrib ,
     this.isha
     });

  PrayerTimeNotifi.fromJson(Map<String, dynamic> json) {
    // hijri = json["hijri"];
     date = json["date"];
     imsak = json["imsak"];
     fajr = json["fajr"];
     syuruk = json["syuruk"];
     dhuhr = json["dhuhr"];
     asr = json["asr"];
     maghrib = json["maghrib"];
     isha = json["isha"];

    var _monthMap = [
      'Jan',
      'Feb',
      'Mac',
      'Apr',
      'Mei',
      'Jun',
      'Jul',
      'Ogos',
      'Sep',
      'Okt',
      'Nov',
      'Dis'
    ];

    String pattern = 'dd-MM-yyyy hh:mm:ss';

    // Changing Text month to its numeric equivalent
    // eg: 2-Okt-2021 will be 2-10-2021

    var _monthNumeric =
        _monthMap.indexWhere((element) => date!.contains(element)) + 1;

    int end = _monthNumeric == 8 ? 7 : 6;

    date = date!.replaceRange(3, end, _monthNumeric.toString());

    times = [
     // DateFormat().parse('$imsak').millisecondsSinceEpoch.(),
      DateTime.parse('$imsak').millisecondsSinceEpoch,
      DateTime.parse('$fajr').millisecondsSinceEpoch,
      DateTime.parse('$syuruk').millisecondsSinceEpoch,
      DateTime
          .parse('$syuruk')
          .add(const Duration(minutes: 28))
          .millisecondsSinceEpoch,
      DateTime.parse('$dhuhr').millisecondsSinceEpoch,
      DateTime.parse('$asr').millisecondsSinceEpoch,
      DateTime.parse('$maghrib').millisecondsSinceEpoch,
      DateTime.parse('$isha').millisecondsSinceEpoch,
    ];
  }



  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['date'] = this.date;
    data['imsak'] = this.imsak;
    data['fajr'] = this.fajr;
    data['syuruk'] = this.syuruk;
    data['dhuhr'] = this.dhuhr;
    data['asr'] = this.asr;
    data['maghrib'] = this.maghrib;
    data['isha'] = this.isha;
    
    return data;
  }

}
